service: default
runtime: python37
default_expiration: 10m
entrypoint: gunicorn -b :8080 main:app
automatic_scaling:
    max_instances: 1

handlers:
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
