service: default
runtime: python37
default_expiration: 10m
automatic_scaling:
    max_instances: 1

handlers:
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
